tree: Events
eras:
  "2022":
    luminosity: 34202 # pb^-1
dbcache: dascache
samples:
MuonEG_C:
  era: "2022C"
  type: data
  group: "data"
  db: das:/MuonEG/Run2022C-PromptNanoAODv10_v1-v1/NANOAOD
  run_range: [355794, 357486]
  certified_lumi_file: https://cms-service-dqmdc.web.cern.ch/CAF/certification/Collisions22/Cert_Collisions2022_355100_362760_Golden.json
  split: 10
  
Muon_C:
  era: "2022C"
  type: data
  group: "data"
  db: das:/Muon/Run2022C-PromptNanoAODv10_v1-v1/NANOAOD
  run_range: [355794, 357486]
  certified_lumi_file: https://cms-service-dqmdc.web.cern.ch/CAF/certification/Collisions22/Cert_Collisions2022_355100_362760_Golden.json
  split: 50

EGamma_C:
  era: "2022C"
  type: data
  group: "data"
  db: das:/EGamma/Run2022C-PromptNanoAODv10_v1-v1/NANOAOD
  run_range: [355794, 357486]
  certified_lumi_file: https://cms-service-dqmdc.web.cern.ch/CAF/certification/Collisions22/Cert_Collisions2022_355100_362760_Golden.json
  split: 100

DoubleMuon_C:
  era: "2022C"
  type: data
  group: "data"
  db: das:/DoubleMuon/Run2022C-PromptNanoAODv10_v1-v1/NANOAOD
  run_range: [355794, 357486]
  certified_lumi_file: https://cms-service-dqmdc.web.cern.ch/CAF/certification/Collisions22/Cert_Collisions2022_355100_362760_Golden.json

SingleMuon_C:
  era: "2022C"
  type: data
  group: "data"
  db: das:/SingleMuon/Run2022C-PromptNanoAODv10_v1-v1/NANOAOD
  run_range: [355794, 357486]
  certified_lumi_file: https://cms-service-dqmdc.web.cern.ch/CAF/certification/Collisions22/Cert_Collisions2022_355100_362760_Golden.json
  split: 10

# Era D

Muon_D:
  era: "2022"
  type: data
  group: "data"
  db: ['das:/Muon/Run2022D-PromptNanoAODv10_v1-v1/NANOAOD', 'das:/Muon/Run2022D-PromptNanoAODv10_v2-v1/NANOAOD']
  run_range: [357734, 358219]
  certified_lumi_file: https://cms-service-dqmdc.web.cern.ch/CAF/certification/Collisions22/Cert_Collisions2022_355100_362760_Golden.json
  split: 15

EGamma_D:
  era: "2022"
  type: data
  group: "data"
  db: ['das:/EGamma/Run2022D-PromptNanoAODv10_v1-v1/NANOAOD','das:/EGamma/Run2022D-PromptNanoAODv10_v2-v1/NANOAOD']
  run_range: [357734, 358219]
  certified_lumi_file: https://cms-service-dqmdc.web.cern.ch/CAF/certification/Collisions22/Cert_Collisions2022_355100_362760_Golden.json
  split: 30


# Era E

Muon_E:
  era: "2022"
  type: data
  group: "data"
  db: das:/Muon/Run2022E-PromptNanoAODv10_v1-v3/NANOAOD
  run_range: [357734, 358219]
  certified_lumi_file: https://cms-service-dqmdc.web.cern.ch/CAF/certification/Collisions22/Cert_Collisions2022_355100_362760_Golden.json
  split: 40
  
EGamma_E:
  era: "2022"
  type: data
  group: "data"
  db: das:/EGamma/Run2022E-PromptNanoAODv10_v1-v2/NANOAOD
  run_range: [357734, 358219]
  certified_lumi_file: https://cms-service-dqmdc.web.cern.ch/CAF/certification/Collisions22/Cert_Collisions2022_355100_362760_Golden.json
  split: 50

# Era F

Muon_F:
  era: "2022"
  type: data
  group: "data"
  db: das:/Muon/Run2022F-PromptNanoAODv10_v1-v2/NANOAOD
  run_range: [357734, 358219]
  certified_lumi_file: https://cms-service-dqmdc.web.cern.ch/CAF/certification/Collisions22/Cert_Collisions2022_355100_362760_Golden.json
  split: 100
  
EGamma_F:
  era: "2022"
  type: data
  group: "data"
  db: das:/EGamma/Run2022F-PromptNanoAODv10_v1-v2/NANOAOD
  run_range: [357734, 358219]
  certified_lumi_file: https://cms-service-dqmdc.web.cern.ch/CAF/certification/Collisions22/Cert_Collisions2022_355100_362760_Golden.json
  split: 130

# Era G

Muon_G:
  era: "2022"
  type: data
  group: "data"
  db: das:/Muon/Run2022G-PromptNanoAODv10_v1-v1/NANOAOD
  run_range: [357734, 358219]
  certified_lumi_file: https://cms-service-dqmdc.web.cern.ch/CAF/certification/Collisions22/Cert_Collisions2022_355100_362760_Golden.json
  split: 15
  
EGamma_G:
  era: "2022"
  type: data
  group: "data"
  db: das:/EGamma/Run2022G-PromptNanoAODv10_v1-v1/NANOAOD
  run_range: [357734, 358219]
  certified_lumi_file: https://cms-service-dqmdc.web.cern.ch/CAF/certification/Collisions22/Cert_Collisions2022_355100_362760_Golden.json
  split: 20
  # bkg #
  !include ./bkg_2022.yml

plotIt:
  configuration:
    width: 800
    height: 600
    margin-left: 0.2
    margin-right: 0.03
    margin-top: 0.05
    margin-bottom: 0.15
    luminosity-label: '%1$.2f fb^{-1} (13.6 TeV)'
    experiment: CMS
    extra-label: Run 3 (2022C)
    error-fill-style: 3154
    error-fill-color: "#ee556270"
    ratio-fit-error-fill-style: 1001
    ratio-fit-error-fill-color: "#aa556270"
    ratio-fit-line-color: "#0B486B"
    yields-table-align: v
  legend:
    position: [0.7, 0.6, 0.91, 0.91]
  groups:
    data:
      legend: data
    TTbar:
      legend: TTbar
      fill-color: "#99ccff"
    DY:
      legend: DY
      fill-color: "#9FFF33"
    WJets:
      legend: WJets
      fill-color: "#FFC300"
    VV:
      legend: VV
      fill-color: "#C900FF"
  plotdefaults:
    y-axis: Events
    log-y: both
    y-axis-show-zero: True
    save-extensions: [pdf]
    show-ratio: False
    sort-by-yields: True
