TTbar:
  era: "2022"
  group: "TTbar"
  db: das:/TTTo2L2Nu_CP5_13p6TeV_powheg-pythia8/Run3Winter22NanoAOD-122X_mcRun3_2021_realistic_v9-v1/NANOAODSIM
  type: mc
  cross-section: 88.4
  generated-events: genEventSumw
  split: 25

DY:
  era: "2022"
  group: "DY"
  db: das:/DYtoLL_NoTau_CP5_13p6TeV_amcatnloFXFX-pythia8/Run3Winter22NanoAOD-122X_mcRun3_2021_realistic_v9-v1/NANOAODSIM
  type: mc
  cross-section: 4515
  generated-events: genEventSumw
  split: 30


DY10to50:
  era: "2022"
  group: "DY"
  db: das:/DYJetsToLL_M-10to50_TuneCP5_13p6TeV-madgraphMLM-pythia8/Run3Winter22NanoAOD-122X_mcRun3_2021_realistic_v9-v1/NANOAODSIM
  type: mc
  cross-section: 19317.5
  generated-events: genEventSumw
  split: 10

WJets:
  era: "2022"
  group: "WJets"
  db: das:/WJetsToLNu_TuneCP5_13p6TeV-madgraphMLM-pythia8/Run3Winter22NanoAOD-122X_mcRun3_2021_realistic_v9-v1/NANOAODSIM
  type: mc
  cross-section: 63199.9
  generated-events: genEventSumw
  split: 30

WW:
  era: "2022"
  group: "VV"
  db: das:/WW_TuneCP5_13p6TeV-pythia8/Run3Winter22NanoAOD-122X_mcRun3_2021_realistic_v9-v1/NANOAODSIM
  type: mc
  cross-section: 173.4
  generated-events: genEventSumw
  split: 10

WZ:
  era: "2022"
  group: "VV"
  db: das:/WZ_TuneCP5_13p6TeV-pythia8/Run3Winter22NanoAOD-122X_mcRun3_2021_realistic_v9-v1/NANOAODSIM
  type: mc
  cross-section: 54.3
  generated-events: genEventSumw
  split: 10

ZZ:
  era: "2022"
  group: "VV"
  db: das:/ZZ_TuneCP5_13p6TeV-pythia8/Run3Winter22NanoAOD-122X_mcRun3_2021_realistic_v9-v1/NANOAODSIM
  type: mc
  cross-section: 16.7
  generated-events: genEventSumw
  split: 2
