#################################
#            DATA               #
#################################

# Era C

MuonEG_C:
  era: "2022C"
  type: data
  group: "data"
  db: das:/MuonEG/Run2022C-PromptNanoAODv10_v1-v1/NANOAOD
  run_range: [355794, 357486]
  certified_lumi_file: https://cms-service-dqmdc.web.cern.ch/CAF/certification/Collisions22/Cert_Collisions2022_355100_362760_Golden.json
  split: 10
  
Muon_C:
  era: "2022C"
  type: data
  group: "data"
  db: das:/Muon/Run2022C-PromptNanoAODv10_v1-v1/NANOAOD
  run_range: [355794, 357486]
  certified_lumi_file: https://cms-service-dqmdc.web.cern.ch/CAF/certification/Collisions22/Cert_Collisions2022_355100_362760_Golden.json
  split: 50

EGamma_C:
  era: "2022C"
  type: data
  group: "data"
  db: das:/EGamma/Run2022C-PromptNanoAODv10_v1-v1/NANOAOD
  run_range: [355794, 357486]
  certified_lumi_file: https://cms-service-dqmdc.web.cern.ch/CAF/certification/Collisions22/Cert_Collisions2022_355100_362760_Golden.json
  split: 100

DoubleMuon_C:
  era: "2022C"
  type: data
  group: "data"
  db: das:/DoubleMuon/Run2022C-PromptNanoAODv10_v1-v1/NANOAOD
  run_range: [355794, 357486]
  certified_lumi_file: https://cms-service-dqmdc.web.cern.ch/CAF/certification/Collisions22/Cert_Collisions2022_355100_362760_Golden.json

SingleMuon_C:
  era: "2022C"
  type: data
  group: "data"
  db: das:/SingleMuon/Run2022C-PromptNanoAODv10_v1-v1/NANOAOD
  run_range: [355794, 357486]
  certified_lumi_file: https://cms-service-dqmdc.web.cern.ch/CAF/certification/Collisions22/Cert_Collisions2022_355100_362760_Golden.json
  split: 10

# Era D

Muon_D:
  era: "2022"
  type: data
  group: "data"
  db: ['das:/Muon/Run2022D-PromptNanoAODv10_v1-v1/NANOAOD', 'das:/Muon/Run2022D-PromptNanoAODv10_v2-v1/NANOAOD']
  run_range: [357734, 358219]
  certified_lumi_file: https://cms-service-dqmdc.web.cern.ch/CAF/certification/Collisions22/Cert_Collisions2022_355100_362760_Golden.json
  split: 15

EGamma_D:
  era: "2022"
  type: data
  group: "data"
  db: ['das:/EGamma/Run2022D-PromptNanoAODv10_v1-v1/NANOAOD','das:/EGamma/Run2022D-PromptNanoAODv10_v2-v1/NANOAOD']
  run_range: [357734, 358219]
  certified_lumi_file: https://cms-service-dqmdc.web.cern.ch/CAF/certification/Collisions22/Cert_Collisions2022_355100_362760_Golden.json
  split: 30


# Era E

Muon_E:
  era: "2022"
  type: data
  group: "data"
  db: das:/Muon/Run2022E-PromptNanoAODv10_v1-v3/NANOAOD
  run_range: [357734, 358219]
  certified_lumi_file: https://cms-service-dqmdc.web.cern.ch/CAF/certification/Collisions22/Cert_Collisions2022_355100_362760_Golden.json
  split: 40
  
EGamma_E:
  era: "2022"
  type: data
  group: "data"
  db: das:/EGamma/Run2022E-PromptNanoAODv10_v1-v2/NANOAOD
  run_range: [357734, 358219]
  certified_lumi_file: https://cms-service-dqmdc.web.cern.ch/CAF/certification/Collisions22/Cert_Collisions2022_355100_362760_Golden.json
  split: 50

# Era F

Muon_F:
  era: "2022"
  type: data
  group: "data"
  db: das:/Muon/Run2022F-PromptNanoAODv10_v1-v2/NANOAOD
  run_range: [357734, 358219]
  certified_lumi_file: https://cms-service-dqmdc.web.cern.ch/CAF/certification/Collisions22/Cert_Collisions2022_355100_362760_Golden.json
  split: 100
  
EGamma_F:
  era: "2022"
  type: data
  group: "data"
  db: das:/EGamma/Run2022F-PromptNanoAODv10_v1-v2/NANOAOD
  run_range: [357734, 358219]
  certified_lumi_file: https://cms-service-dqmdc.web.cern.ch/CAF/certification/Collisions22/Cert_Collisions2022_355100_362760_Golden.json
  split: 130

# Era G

Muon_G:
  era: "2022"
  type: data
  group: "data"
  db: das:/Muon/Run2022G-PromptNanoAODv10_v1-v1/NANOAOD
  run_range: [357734, 358219]
  certified_lumi_file: https://cms-service-dqmdc.web.cern.ch/CAF/certification/Collisions22/Cert_Collisions2022_355100_362760_Golden.json
  split: 15
  
EGamma_G:
  era: "2022"
  type: data
  group: "data"
  db: das:/EGamma/Run2022G-PromptNanoAODv10_v1-v1/NANOAOD
  run_range: [357734, 358219]
  certified_lumi_file: https://cms-service-dqmdc.web.cern.ch/CAF/certification/Collisions22/Cert_Collisions2022_355100_362760_Golden.json
  split: 20

