tree: Events
eras:
  "2022":
    luminosity: 7865 # pb^-1
dbcache: dascache
samples:
  EGamma:
    era: "2022CD"
    type: data
    group: "data"
    db: ['das:/EGamma/Run2022C-PromptNanoAODv10_v1-v1/NANOAOD', 'das:/EGamma/Run2022D-PromptNanoAODv10_v1-v1/NANOAOD','das:/EGamma/Run2022D-PromptNanoAODv10_v2-v1/NANOAOD']
    run_range: [355794, 358219]
    certified_lumi_file: https://cms-service-dqmdc.web.cern.ch/CAF/certification/Collisions22/Cert_Collisions2022_355100_362760_Golden.json
    split: 175

plotIt:
  configuration:
    width: 800
    height: 600
    margin-left: 0.2
    margin-right: 0.03
    margin-top: 0.05
    margin-bottom: 0.15
    luminosity-label: '%1$.2f fb^{-1} (13.6 TeV)'
    experiment: CMS
    extra-label: Run 3 (2022) - Work in progress
    error-fill-style: 3154
    error-fill-color: "#ee556270"
    yields-table-align: v
  legend:
    position: [0.7, 0.6, 0.91, 0.91]
  groups:
    data:
      legend: data.
      fill-color: "#99ccff"
  plotdefaults:
    y-axis: Events
    log-y: both
    y-axis-show-zero: True
    save-extensions: [pdf]
    sort-by-yields: True
