tree: Events
eras:
  "2022F":
    luminosity: 17610 # pb^-1
dbcache: dascache
samples:

  Muon:
    era: "2022F"
    type: data
    group: "data"
    db: das:/Muon/Run2022F-PromptNanoAODv10_v1-v2/NANOAOD
    run_range: [360332, 362180]
    certified_lumi_file: https://cms-service-dqmdc.web.cern.ch/CAF/certification/Collisions22/Cert_Collisions2022_355100_362760_Golden.json
    split: 60
    
  EGamma:
    era: "2022F"
    type: data
    group: "data"
    db: das:/EGamma/Run2022F-PromptNanoAODv10_v1-v2/NANOAOD
    run_range: [360332, 362180]
    certified_lumi_file: https://cms-service-dqmdc.web.cern.ch/CAF/certification/Collisions22/Cert_Collisions2022_355100_362760_Golden.json
    split: 80

  TTbar:
    era: "2022F"
    group: "TTbar"
    db: das:/TTTo2L2Nu_CP5_13p6TeV_powheg-pythia8/Run3Winter22NanoAOD-122X_mcRun3_2021_realistic_v9-v1/NANOAODSIM
    type: mc
    cross-section: 88.4
    generated-events: genEventSumw
    split: 25

  DY:
    era: "2022F"
    group: "DY"
    db: das:/DYtoLL_NoTau_CP5_13p6TeV_amcatnloFXFX-pythia8/Run3Winter22NanoAOD-122X_mcRun3_2021_realistic_v9-v1/NANOAODSIM
    type: mc
    cross-section: 4515
    generated-events: genEventSumw
    split: 27

  WJets:
    era: "2022F"
    group: "WJets"
    db: das:/WJetsToLNu_TuneCP5_13p6TeV-madgraphMLM-pythia8/Run3Winter22NanoAOD-122X_mcRun3_2021_realistic_v9-v1/NANOAODSIM
    type: mc
    cross-section: 63199.9
    generated-events: genEventSumw
    split: 30

  WW:
    era: "2022F"
    group: "VV"
    db: das:/WW_TuneCP5_13p6TeV-pythia8/Run3Winter22NanoAOD-122X_mcRun3_2021_realistic_v9-v1/NANOAODSIM
    type: mc
    cross-section: 173.4
    generated-events: genEventSumw
    split: 10

  WZ:
    era: "2022F"
    group: "VV"
    db: das:/WZ_TuneCP5_13p6TeV-pythia8/Run3Winter22NanoAOD-122X_mcRun3_2021_realistic_v9-v1/NANOAODSIM
    type: mc
    cross-section: 54.3
    generated-events: genEventSumw
    split: 10

  ZZ:
    era: "2022F"
    group: "VV"
    db: das:/ZZ_TuneCP5_13p6TeV-pythia8/Run3Winter22NanoAOD-122X_mcRun3_2021_realistic_v9-v1/NANOAODSIM
    type: mc
    cross-section: 16.7
    generated-events: genEventSumw
    split: 2

plotIt:
  configuration:
    width: 800
    height: 600
    margin-left: 0.2
    margin-right: 0.03
    margin-top: 0.05
    margin-bottom: 0.15
    luminosity-label: '%1$.2f fb^{-1} (13.6 TeV)'
    experiment: CMS
    extra-label: Run 3 (2022F)
    error-fill-style: 3154
    error-fill-color: "#ee556270"
    ratio-fit-error-fill-style: 1001
    ratio-fit-error-fill-color: "#aa556270"
    ratio-fit-line-color: "#0B486B"
    yields-table-align: v
  legend:
    position: [0.7, 0.6, 0.91, 0.91]
  groups:
    data:
      legend: data
    TTbar:
      legend: TTbar
      fill-color: "#99ccff"
    DY:
      legend: DY
      fill-color: "#9FFF33"
    WJets:
      legend: WJets
      fill-color: "#FFC300"
    VV:
      legend: VV
      fill-color: "#C900FF"
  plotdefaults:
    y-axis: Events
    log-y: both
    y-axis-show-zero: True
    save-extensions: [pdf]
    show-ratio: False
    sort-by-yields: True
